export const S3_KEYS = {
  hero: "aying_site_jpg/hero-bg.jpg",
  about: "aying_site_jpg/self_3.jpeg",
  portfolio: {
    bridal: [
      "aying_site_jpg/bridal_1.jpg",
      "aying_site_jpg/bridal_2.jpg",
      "aying_site_jpg/bridal_3.jpg",
      "aying_site_jpg/bridal_4.jpg",
      "aying_site_jpg/bridal_5.jpg",
      "aying_site_jpg/bridal_6.jpg",
      "aying_site_jpg/bridal_7.jpg",
      "aying_site_jpg/bridal_8.jpg",
      "aying_site_jpg/bridal_9.jpg",
      "aying_site_jpg/bridal_10.jpg",
      "aying_site_jpg/bridal_11.jpg",
      "aying_site_jpg/bridal_12.jpg",
    ],
    celebrity: [
      "aying_site_jpg/celeb_2.jpg",
      "aying_site_jpg/celeb_3.jpg",
      "aying_site_jpg/celeb_4.jpg",
      "aying_site_jpg/celeb_5.jpg",
      "aying_site_jpg/celeb_6.jpg",
      "aying_site_jpg/celeb_7.jpg",
    ],
    editorial: [
      "aying_site_jpg/earth_1.jpg",
      "aying_site_jpg/earth_2.jpg",
      "aying_site_jpg/earth_3.jpg",
      "aying_site_jpg/earth_4.jpg",
    ],
    model: [
      "aying_site_jpg/model_1.jpeg",
      "aying_site_jpg/model_2.jpg",
      "aying_site_jpg/model_3.jpg",
      "aying_site_jpg/model_4.jpg",
      "aying_site_jpg/model_5.jpg",
      "aying_site_jpg/model_6.jpg",
      "aying_site_jpg/model_8.jpg",
      "aying_site_jpg/model_9.jpg",
      "aying_site_jpg/model_10.jpg",
      "aying_site_jpg/model_11.jpg",
      "aying_site_jpg/model_12.jpg",
      "aying_site_jpg/model_13.jpg",
      "aying_site_jpg/model_14.jpg",
      "aying_site_jpg/model_15.jpg",
      "aying_site_jpg/model_16.jpg",
      "aying_site_jpg/model_17.jpg",
      "aying_site_jpg/model_18.jpg",
      "aying_site_jpg/model_19.jpg",
      "aying_site_jpg/model_20.jpg",
      "aying_site_jpg/model_21.jpg",
      "aying_site_jpg/model_22.jpg",
      "aying_site_jpg/model_23.jpg",
      "aying_site_jpg/model_24.jpg",
    ],
    runway: [
      "aying_site_jpg/runway_1.jpg",
      "aying_site_jpg/runway_2.jpg",
      "aying_site_jpg/runway_3.jpg",
      "aying_site_jpg/runway_4.jpg",
      "aying_site_jpg/runway_6.jpg",
      "aying_site_jpg/runway_11.jpg",
      "aying_site_jpg/runway_13.jpg",
      "aying_site_jpg/runway_14.jpg",
      "aying_site_jpg/runway_15.jpg",
      "aying_site_jpg/runway_16.jpg",
      "aying_site_jpg/runway_17.jpg",
      "aying_site_jpg/runway_18.jpg",
    ],
  },
  videos: {
    runway5: "aying_site_vids/runway_5.mp4",
    runway7: "aying_site_vids/runway_7.mp4",
    runway8: "aying_site_vids/runway_8.mp4",
    runway9: "aying_site_vids/runway_9.mp4",
    runway10: "aying_site_vids/runway_10.mp4",
    runway12: "aying_site_vids/runway_12.mp4",
  },
} as const;
